version: '3.3'

services:
  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - app
    volumes:
    - static:/var/www/html
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8080:80

  app:
    depends_on:
      - db
    build: .
    volumes:
    - static:/app/static
  db:
    image: postgres:13-alpine3.13
    environment:
      POSTGRES_PASSWORD: donorgrid
      POSTGRES_DB: donorgrid
      POSTGRES_USER: donorgrid


volumes:
  static:
    driver: local
